services:
  nginx:
    image: nginx:stable
    ports:
      - "0.0.0.0:8080:80"
    volumes:
      - ./docker/configs/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./packages/api:/app
    networks:
      - internal
    depends_on:
      - api
      - pwa

  api:
    build:
      context: ./docker
      target: php
    volumes:
      - ./docker/configs/php/default.ini:/usr/local/etc/php/conf.d/app.ini:ro 
      - ./packages/api:/app
    networks:
      - internal
    depends_on:
      - db
      
  pwa:
    image: node:20-alpine3.18
    expose:
      - 5173
    volumes:
      - ./:/app
    working_dir: /app
    command: yarn workspace pwa run dev --host
    networks:
      - internal
      
  db:
    image: mysql:5.7
    healthcheck:
      test: "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
      interval: 5s
      timeout: 5s
      retries: 5
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rss-app
      - MYSQL_USER=rss-app-user
      - MYSQL_PASSWORD=rss-app-password
    ports:
      - "3306:3306"
    networks:
      - internal

networks:
  internal:
    driver: bridge
